insert into demo_products (
  id,
  name,
  brand,
  category,
  volume,
  expiration_date,
  production_date,
  notes,
  demo_photo_uri,
  barcode,
  primary_ocr_cues,
  secondary_ocr_cues,
  packaging_color,
  ingredients_summary,
  routine_advice,
  sort_order
)
values
  (
    'demo_001_suncut',
    'Suncut UV Perfect Milk SPF50+ PA++++',
    'KOSÉ Cosmeport',
    'sunscreen',
    '50ml',
    '2027-02-28',
    null,
    'Super waterproof milk sunscreen for face and body; shake well before use.',
    'require(''../assets/demo/suncut_uv_milk.jpg'')',
    null,
    array['SUNCUT', 'UV', 'PERFECT MILK'],
    array['SPF50+', 'PA++++', 'KOSÉ'],
    'yellow-gold',
    'A waterproof Japanese sunscreen milk that combines high-SPF UV filters with lightweight film-formers for strong outdoor protection.',
    'Shake well, apply generously as the last step of your morning skincare, and reapply after sweating, swimming, or towel-drying.',
    1
  ),
  (
    'demo_002_chanel_uv',
    'UV Essentiel Protection Globale SPF 50+/PA++++',
    'CHANEL',
    'sunscreen',
    '30ml',
    '2026-12-31',
    null,
    'Global protection formula enriched with ginger from Madagascar; made in France.',
    'require(''../assets/demo/chanel_uv_essentiel.jpg'')',
    '3145891418989',
    array['CHANEL', 'UV ESSENTIEL', 'SPF 50+'],
    array['PROTECTION GLOBALE', 'GLOBAL PROTECTION', '30 ml'],
    'white-silver',
    'A high-protection daily UV fluid featuring broad-spectrum sunscreen filters with antioxidant botanical extracts, including ginger, to help defend against environmental stress.',
    'Apply evenly as the final skincare step before makeup, and reapply every two hours when exposed to direct sunlight.',
    2
  ),
  (
    'demo_003_fresh_toner',
    'Rose Deep Hydration Facial Toner',
    'fresh',
    'skincare',
    '250ml',
    '2027-11-30',
    null,
    'Hydrating facial toner with visible rose petals; removes impurities and softens skin.',
    'require(''../assets/demo/fresh_rose_toner.jpg'')',
    '809280126758',
    array['fresh', 'ROSE', 'DEEP HYDRATION'],
    array['FACIAL TONER', 'REMOVES IMPURITIES', '250ml'],
    'transparent-brown',
    'A hydrating toner with rose fruit extract, rosewater, and humectants such as hyaluronic acid to soften skin while sweeping away residual impurities.',
    'Use after cleansing by applying with a cotton pad or palms, then follow with serum and moisturizer morning and night.',
    3
  ),
  (
    'demo_004_skii_aura',
    'Genoptics Ultraura Essence',
    'SK-II',
    'skincare',
    '50ml',
    '2026-06-30',
    '2023-06-01',
    'Brightening essence made in Japan.',
    'require(''../assets/demo/skii_genoptics_ultraura_essence.jpg'')',
    '4979006085747',
    array['SK-II', 'GENOPTICS', 'ULTRAURA ESSENCE'],
    array['50mL', 'Made in Japan', 'Ultraura'],
    'dark-red',
    'A brightening essence built around SK-II’s PITERA technology and a pigment-targeting complex to support clarity and even-looking skin tone.',
    'Apply after toner and before moisturizer, smoothing a few drops across the face morning and evening for best brightening results.',
    4
  )
on conflict (id) do update
set
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  volume = excluded.volume,
  expiration_date = excluded.expiration_date,
  production_date = excluded.production_date,
  notes = excluded.notes,
  demo_photo_uri = excluded.demo_photo_uri,
  barcode = excluded.barcode,
  primary_ocr_cues = excluded.primary_ocr_cues,
  secondary_ocr_cues = excluded.secondary_ocr_cues,
  packaging_color = excluded.packaging_color,
  ingredients_summary = excluded.ingredients_summary,
  routine_advice = excluded.routine_advice,
  sort_order = excluded.sort_order,
  updated_at = now();
