insert into demo_products (
  id,
  name,
  brand,
  category,
  volume,
  expiration_date,
  production_date,
  notes,
  demo_photo_uri,
  barcode,
  primary_ocr_cues,
  secondary_ocr_cues,
  packaging_color,
  ingredients_summary,
  routine_advice,
  sort_order
)
values (
  'demo_005_hada_labo_gokujyun_milk',
  'Gokujyun Hydrating Milk',
  'Hada Labo',
  'skincare',
  '90ml',
  '2027-12-31',
  null,
  'Lightweight moisturizing milk/emulsion with multiple hyaluronic acids; fragrance-free, colorant-free, mineral oil-free, alcohol-free, and paraben-free.',
  'require(''../assets/demo/hada_labo_gokujyun_milk.jpg'')',
  '4895186013007',
  array['Hada Labo', 'GOKU JYUN', '極潤'],
  array['保濕乳液', '90ml', '肌研'],
  'white-blue',
  'A lightweight hydrating emulsion centered on multiple forms of hyaluronic acid to replenish surface moisture, soften skin, and support a smoother barrier.',
  'Apply after toner and serum, then smooth 1 to 2 pumps across the face as your lightweight moisturizing step morning and night.',
  5
)
on conflict (id) do update
set
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  volume = excluded.volume,
  expiration_date = excluded.expiration_date,
  production_date = excluded.production_date,
  notes = excluded.notes,
  demo_photo_uri = excluded.demo_photo_uri,
  barcode = excluded.barcode,
  primary_ocr_cues = excluded.primary_ocr_cues,
  secondary_ocr_cues = excluded.secondary_ocr_cues,
  packaging_color = excluded.packaging_color,
  ingredients_summary = excluded.ingredients_summary,
  routine_advice = excluded.routine_advice,
  sort_order = excluded.sort_order,
  updated_at = now();
