insert into demo_products (
  id,
  name,
  brand,
  category,
  volume,
  expiration_date,
  production_date,
  notes,
  demo_photo_uri,
  barcode,
  primary_ocr_cues,
  secondary_ocr_cues,
  packaging_color,
  ingredients_summary,
  routine_advice,
  sort_order
)
values (
  'demo_006_neutrogena_hydro_boost_water_gel_50g',
  'Hydro Boost Hyaluronic Acid Water Gel',
  'Neutrogena',
  'skincare',
  '50g',
  '2029-01-20',
  '2026-01-21',
  'Refillable Hydro Boost water gel jar for AM/PM use. Compatible with Hydro Boost refill pods only. Batch lot: 004. Label code: 128870.',
  'require(''../assets/demo/neutrogena_hydro_boost_water_gel_50g.jpg'')',
  null,
  array['Neutrogena', 'HYDRO BOOST', 'WATER GEL', 'HYALURONIC ACID'],
  array['50g', '004', '128870', 'Refillable'],
  'translucent-blue',
  'A lightweight gel moisturizer with hyaluronic acid and humectants that helps attract water, support hydration, and leave skin feeling refreshed.',
  'Apply to clean skin morning and night after toner or serum, then seal with sunscreen in the daytime.',
  6
)
on conflict (id) do update
set
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  volume = excluded.volume,
  expiration_date = excluded.expiration_date,
  production_date = excluded.production_date,
  notes = excluded.notes,
  demo_photo_uri = excluded.demo_photo_uri,
  barcode = excluded.barcode,
  primary_ocr_cues = excluded.primary_ocr_cues,
  secondary_ocr_cues = excluded.secondary_ocr_cues,
  packaging_color = excluded.packaging_color,
  ingredients_summary = excluded.ingredients_summary,
  routine_advice = excluded.routine_advice,
  sort_order = excluded.sort_order,
  updated_at = now();
